# Generated by Django 4.2.13 on 2024-06-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("OCRApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("extracted_text", models.TextField(blank=True)),
                ("bold_words", models.TextField(blank=True)),
                ("image_base64", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
